/**
 * Configuration & Secrets Recovery v1 — canonical configuration recovery
 * register. See docs/configuration-and-secrets-recovery-v1.md.
 *
 * VALUE-FREE BY DESIGN: this file is metadata only. Nothing in
 * `ConfigRecoveryEntry` can hold an actual secret value, example
 * Production value, hash, fingerprint, or ciphertext — there is no
 * `value`/`secret`/`passwordValue`/`privateKeyValue`/`tokenValue` field
 * anywhere on this type, and there never should be (see
 * `register.test.ts`'s own structural guard for this). Every entry below
 * is grounded in either a real `process.env.<NAME>` read site in this
 * repository or an existing, already-reviewed document — never guessed
 * from a plausible-sounding name.
 *
 * This register deliberately keeps THREE separate concepts apart (see
 * docs/configuration-and-secrets-recovery-v1.md, "Three different
 * concepts" for the full explanation):
 *
 * 1. `runtimeSource` — where the RUNNING service currently reads the
 *    value from today (e.g. "Vercel project environment variable").
 * 2. `recoveryClass` (+ `lossImpact`/`rotationImpact`) — HOW the value
 *    would be reconstructed after loss.
 * 3. `authoritativeRecoverySourceStatus` — WHERE the recoverable
 *    material is independently held, separate from the runtime. For
 *    every real secret in this register today, that is
 *    `"NOT_YET_SELECTED"` — a Vercel environment variable is a RUNTIME
 *    SOURCE, never treated here as an independent recovery source
 *    merely because it currently holds the value, and GitHub is never
 *    treated as a secret-value recovery source at all (see
 *    docs/configuration-and-secrets-recovery-v1.md's own explicit
 *    statement of this).
 *
 * ALIAS MODEL — one entry's `aliasNames` means ONE thing, always:
 * alternative/fallback representations of the SAME logical
 * configuration value, where the running code checks them in a fixed
 * priority order and only ONE is ever actually expected to be set (the
 * LTI `*_B64`/`*_PATH`/raw key triples; `NEXT_PUBLIC_SUPABASE_URL` as
 * `SUPABASE_URL`'s fallback; `GIT_COMMIT_SHA` as
 * `VERCEL_GIT_COMMIT_SHA`'s fallback). It does NOT mean "these names are
 * read independently but I grouped them to shorten the register" — that
 * was a real modelling error found in an earlier pass (four independent
 * `TETHER_BLOCK_*` lockdown toggles, `LTI_TOOL_NAME`/`LTI_TOOL_DESCRIPTION`,
 * and `SUPABASE_ACCESS_TOKEN`/`SUPABASE_DB_PASSWORD` were all previously
 * mis-grouped this way) — because the audit's own "is this entry
 * represented in `.env.example`" check is satisfied by ANY ONE
 * name/alias being present, so a genuinely independent variable's own
 * deletion from the template could go completely undetected as long as
 * a sibling it was wrongly grouped with remained. Every independent
 * variable now has its own entry with `aliasNames: []`, even where that
 * makes this file longer. `register.test.ts`'s `[12]` test locks every
 * remaining non-empty `aliasNames` group in this file against an
 * explicit allowlist of genuine alternate-representation groups, so a
 * future accidental re-grouping is caught immediately rather than
 * inferred from variable-name similarity.
 */

/** Where the running service currently reads this configuration item's value from. */
export type ConfigCategory =
  | "ACTIVE_PRODUCTION_RUNTIME"
  | "OPTIONAL_PRODUCTION_RUNTIME"
  | "OPERATOR_MAINTENANCE_ONLY"
  | "LOCAL_DEVELOPMENT_ONLY"
  | "PROVIDER_PLATFORM_SUPPLIED"
  | "FUTURE_NOT_PROVISIONED"
  | "DEPRECATED_DOCUMENTED_NOT_USED";

/**
 * HOW this item would be reconstructed after loss — see this file's own
 * doc comment. `null` only for items where a recovery class genuinely
 * does not apply yet (e.g. `FUTURE_NOT_PROVISIONED` items, which have no
 * live value to recover).
 */
export type RecoveryClass = "PRESERVE_EXACT_VALUE" | "ROTATE_OR_REISSUE" | "RECONSTRUCT_CONFIGURATION" | "PROVIDER_LOOKUP" | "BOOTSTRAP_ONLY" | "FUTURE_NOT_PROVISIONED";

/** Whether this item's VALUE (not its name) is sensitive. Never used to decide whether the NAME can appear here — names always can. */
export type ConfigSensitivity = "SECRET" | "NON_SECRET";

/** Where the running service reads this value from today. Deliberately distinct from `authoritativeRecoverySourceStatus` — see this file's own doc comment, concept 1 vs 3. */
export type RuntimeSource = "VERCEL_ENVIRONMENT_VARIABLE" | "LOCAL_OPERATOR_ENVIRONMENT" | "PROVIDER_SUPPLIED_AT_RUNTIME" | "BUILD_TOOLING_SUPPLIED" | "NOT_YET_PROVISIONED" | "NOT_APPLICABLE";

export type ConfigEnvironment = "PRODUCTION_AND_PREVIEW" | "PRODUCTION_ONLY" | "PREVIEW_ONLY" | "LOCAL_ONLY" | "ALL_DEPLOYMENTS" | "NOT_APPLICABLE";

/**
 * Every real secret in this register is currently `"NOT_YET_SELECTED"` —
 * see this file's own doc comment. Kept as a literal union (not a bare
 * string) so a future, deliberate change to the actual set of possible
 * statuses is a visible type change, not a silent string edit.
 */
export type AuthoritativeRecoverySourceStatus = "NOT_YET_SELECTED";

export type ConfigRecoveryEntry = {
  /** The env var name exactly as read via `process.env.<NAME>`. */
  name: string;
  /**
   * ONE meaning, never overloaded: alternative/fallback representations
   * of the SAME logical configuration value — e.g. `LTI_PRIVATE_KEY_B64`
   * / `LTI_PRIVATE_KEY_PATH` / `LTI_PRIVATE_KEY` (checked in that
   * priority order, only ONE is ever actually set), or
   * `NEXT_PUBLIC_SUPABASE_URL` as `SUPABASE_URL`'s fallback. See this
   * module's own "Alias model" doc comment for the full test — the short
   * version: if the running code reads two names INDEPENDENTLY of each
   * other (each with its own default, each meaningfully settable at the
   * same time as the other), they are NOT aliases of one entry — they
   * are two separate `ConfigRecoveryEntry` objects, even if that makes
   * the register longer. Never use this field merely to shorten the
   * register. `register.test.ts`'s own `[12]` test locks every
   * non-empty group in this file against an explicit allowlist, so a
   * future accidental re-grouping is caught immediately, not inferred
   * from name similarity.
   */
  aliasNames: string[];
  category: ConfigCategory;
  sensitivity: ConfigSensitivity;
  environment: ConfigEnvironment;
  runtimeSource: RuntimeSource;
  recoveryClass: RecoveryClass | null;
  /** True if the running application/feature this entry gates cannot function correctly without it — never true merely because a value "should probably" be set. */
  required: boolean;
  /** The specific capability this item affects — never "the app" as a whole unless genuinely core-required. */
  affectedCapability: string;
  /** What becomes unavailable or inconsistent if this value is lost and (where applicable) replaced with a different one. Required for every SECRET entry with a non-null recoveryClass — see register.test.ts. */
  lossImpact: string;
  /** What happens to already-existing data/state if this value is deliberately rotated to a NEW value. `null` only where rotation impact is not a meaningful question for this entry (e.g. a plain non-secret URL). */
  rotationImpact: string | null;
  /** Another register entry name this one's recovery depends on (e.g. `TETHER_SEB_KEY_ENCRYPTION_ACTIVE_KEY_ID` depends on a key of the same id existing in `TETHER_SEB_KEY_ENCRYPTION_KEYS_JSON`). `null` if none. */
  recoveryDependency: string | null;
  /** Whether this NAME is expected to appear in `.env.example` (with a blank/synthetic value) — false for FUTURE_NOT_PROVISIONED items and for platform-auto-supplied build metadata that an operator never sets by hand. */
  templatePresenceExpected: boolean;
  /** File:line or documentation path this entry is grounded in. */
  sourceReference: string;
  /** See this file's own doc comment, concept 3. Every SECRET entry today is `"NOT_YET_SELECTED"`. */
  authoritativeRecoverySourceStatus: AuthoritativeRecoverySourceStatus | null;
  /** Free-text clarification, only when genuinely needed beyond the structured fields above. */
  notes?: string;
};

const AUTHORITATIVE_RECOVERY_SOURCE_NOT_YET_SELECTED: AuthoritativeRecoverySourceStatus = "NOT_YET_SELECTED";

export const CONFIGURATION_RECOVERY_REGISTER: readonly ConfigRecoveryEntry[] = [
  // ── Core / database ──────────────────────────────────────────────────
  {
    name: "DATABASE_URL",
    aliasNames: [],
    category: "ACTIVE_PRODUCTION_RUNTIME",
    sensitivity: "SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "ROTATE_OR_REISSUE",
    required: true,
    affectedCapability: "Every database-backed request (Prisma connection string).",
    lossImpact: "The application cannot connect to the database at all until a working connection string is restored. The password portion is not independently recoverable if lost — it must be reset via the Supabase dashboard (Project Settings → Database), which the app's own historical data does not depend on (row/table content is unaffected by a password reset).",
    rotationImpact: "Resetting the database password (e.g. via the Supabase dashboard) requires updating DATABASE_URL (and BACKUP_SOURCE_DATABASE_URL, if separately set) everywhere it is configured, and a redeploy. Existing data is unaffected — a Postgres password reset does not re-encrypt or invalidate stored rows.",
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "src/lib/prisma.ts; docs/deployment-vercel-supabase.md",
    authoritativeRecoverySourceStatus: AUTHORITATIVE_RECOVERY_SOURCE_NOT_YET_SELECTED,
  },
  {
    name: "DATABASE_POOL_MAX",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Per-invocation Prisma pg pool size tuning under concurrent exam traffic.",
    lossImpact: "Falls back to a safe default (3) if unset — no functional loss, only a possible performance-tuning regression under load.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "src/lib/prisma.ts:59",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "SHADOW_DATABASE_URL",
    aliasNames: [],
    category: "LOCAL_DEVELOPMENT_ONLY",
    sensitivity: "SECRET",
    environment: "LOCAL_ONLY",
    runtimeSource: "LOCAL_OPERATOR_ENVIRONMENT",
    recoveryClass: "ROTATE_OR_REISSUE",
    required: false,
    affectedCapability: "`prisma migrate dev` only — not used by `prisma db push` or in Production.",
    lossImpact: "None in Production or Preview. A local developer without it simply cannot run `prisma migrate dev` against a database requiring a shadow database.",
    rotationImpact: "A fresh local/disposable database connection string; no historical data depends on it.",
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: ".env.example; docs/deployment-vercel-supabase.md",
    authoritativeRecoverySourceStatus: null,
  },

  // ── Auth ──────────────────────────────────────────────────────────────
  {
    name: "AUTH_SECRET",
    aliasNames: [],
    category: "ACTIVE_PRODUCTION_RUNTIME",
    sensitivity: "SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "ROTATE_OR_REISSUE",
    required: true,
    affectedCapability: "NextAuth (v5) session signing/verification for every authenticated request.",
    lossImpact: "If lost with no backup, a freshly generated replacement can be issued — the application does not fail to function, but every currently active session becomes invalid.",
    rotationImpact: "Every currently active session is invalidated immediately — all logged-in users are signed out and must log in again. No other historical data is affected.",
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: ".env.example; docs/deployment-vercel-supabase.md",
    authoritativeRecoverySourceStatus: AUTHORITATIVE_RECOVERY_SOURCE_NOT_YET_SELECTED,
  },
  {
    name: "APP_URL",
    aliasNames: [],
    category: "ACTIVE_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: true,
    affectedCapability: "Canvas-facing redirect_uri/target_link_uri built by /api/lti/login and /api/lti/config; PRODUCTION_ORIGIN_MISSING readiness check.",
    lossImpact: "Must exactly match the deployed HTTPS domain and Canvas's registered redirect URI — reconstructible from the known deployment domain, not a secret.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "src/lib/env/readiness.ts; docs/deployment-vercel-supabase.md",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "VERCEL_URL",
    aliasNames: [],
    category: "PROVIDER_PLATFORM_SUPPLIED",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "PROVIDER_SUPPLIED_AT_RUNTIME",
    recoveryClass: null,
    required: false,
    affectedCapability: "Fallback for APP_URL in src/lib/appOrigin.ts's resolveLtiToolOrigin/resolveTrustedExternalOrigin — lets Preview deployments resolve a trusted origin without hand-configuring APP_URL per deploy.",
    lossImpact: "Not applicable — supplied automatically by Vercel; only consulted when APP_URL is unset.",
    rotationImpact: null,
    recoveryDependency: "APP_URL",
    templatePresenceExpected: false,
    sourceReference: "src/lib/appOrigin.ts:59,83",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "NEXT_PUBLIC_APP_URL",
    aliasNames: [],
    category: "DEPRECATED_DOCUMENTED_NOT_USED",
    sensitivity: "NON_SECRET",
    environment: "NOT_APPLICABLE",
    runtimeSource: "NOT_APPLICABLE",
    recoveryClass: null,
    required: false,
    affectedCapability: "None — listed in .env.example for forward-compatibility only; no current process.env.NEXT_PUBLIC_APP_URL read site exists.",
    lossImpact: "None — setting or omitting it has no effect on any current code path.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: false,
    sourceReference: "docs/deployment-vercel-supabase.md (explicitly documents this is not read by any code path)",
    authoritativeRecoverySourceStatus: null,
    notes: "Kept in this register precisely so it is not silently reintroduced as an ACTIVE entry — it remains a documented-but-unused name, not a gap.",
  },

  // ── Exam integrity secrets ────────────────────────────────────────────
  {
    name: "EXAM_BINDING_HMAC_SECRET",
    aliasNames: [],
    category: "ACTIVE_PRODUCTION_RUNTIME",
    sensitivity: "SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "PRESERVE_EXACT_VALUE",
    required: true,
    affectedCapability: "Exam session-binding token/IP-prefix/user-agent hashing (src/lib/sessionBinding.ts) for the exam session-binding integrity signal.",
    lossImpact: "If lost and replaced with a different value, every previously stored session-binding hash becomes permanently uncomparable against newly computed hashes — historical device-continuity evidence for exams taken before the change becomes unusable for comparison purposes. The current code (src/lib/sessionBinding.ts, resolveHmacSecret()) FAILS CLOSED if this is missing/whitespace-only, throwing rather than falling back to a random per-process value — .env.example's own comment text describing a random-fallback behaviour is stale relative to the actual current code (a real finding this register corrects, not a re-guess).",
    rotationImpact: "Breaks comparability of all session-binding hashes computed before the rotation against any computed after it — this is a genuine historical-integrity-evidence loss, not merely an inconvenience.",
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "src/lib/sessionBinding.ts; .env.example",
    authoritativeRecoverySourceStatus: AUTHORITATIVE_RECOVERY_SOURCE_NOT_YET_SELECTED,
  },
  {
    name: "NETWORK_EVIDENCE_SALT",
    aliasNames: [],
    category: "ACTIVE_PRODUCTION_RUNTIME",
    sensitivity: "SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "PRESERVE_EXACT_VALUE",
    required: true,
    affectedCapability: "HMAC-SHA256 pseudonymisation of stored IP addresses for network-evidence comparison (src/lib/networkEvidence.ts).",
    lossImpact: "If lost and replaced with a different value, previously stored pseudonymised IP hashes become permanently uncomparable against newly computed hashes for the same real IP — historical network-evidence comparisons across the change point become unusable. The current code (src/lib/networkEvidence.ts, hashIp()) FAILS CLOSED if this is missing/whitespace-only, throwing rather than falling back to a random per-process salt — .env.example's own comment text describing a random-fallback behaviour is likewise stale relative to the actual current code.",
    rotationImpact: "Breaks comparability of IP-hash evidence recorded before the rotation against evidence recorded after it.",
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "src/lib/networkEvidence.ts; .env.example",
    authoritativeRecoverySourceStatus: AUTHORITATIVE_RECOVERY_SOURCE_NOT_YET_SELECTED,
  },

  // ── LTI / Canvas (optional module) ───────────────────────────────────
  {
    name: "LTI_CLIENT_ID",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "PROVIDER_LOOKUP",
    required: false,
    affectedCapability: "Canvas LTI 1.3 launch/OIDC flow.",
    lossImpact: "Retrievable from the institution's Canvas Developer Key configuration — not independently secret material this app must preserve.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "src/lib/env/readiness.ts; docs/deployment-vercel-supabase.md",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "LTI_DEPLOYMENT_ID",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "PROVIDER_LOOKUP",
    required: false,
    affectedCapability: "Canvas LTI 1.3 launch/OIDC flow.",
    lossImpact: "Retrievable from the institution's Canvas Developer Key configuration.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "src/lib/env/readiness.ts; docs/deployment-vercel-supabase.md",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "LTI_PLATFORM_ISSUER",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Canvas LTI 1.3 OIDC flow.",
    lossImpact: "A well-known default (canvas.instructure.com) covers the common case; self-hosted Canvas instances need their own documented URL.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "src/lib/env/readiness.ts; .env.example",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "LTI_PLATFORM_OIDC_AUTH",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Canvas LTI 1.3 OIDC flow.",
    lossImpact: "Well-known default covers canvas.instructure.com.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "src/lib/env/readiness.ts; .env.example",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "LTI_PLATFORM_JWKS",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Canvas LTI 1.3 JWT verification.",
    lossImpact: "Well-known default covers canvas.instructure.com.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "src/lib/env/readiness.ts; .env.example",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "LTI_TOKEN_ENDPOINT",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Canvas Assignment and Grade Services (AGS) passback.",
    lossImpact: "Well-known default covers canvas.instructure.com.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "src/lib/env/readiness.ts; .env.example",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "LTI_PRIVATE_KEY_B64",
    aliasNames: ["LTI_PRIVATE_KEY_PATH", "LTI_PRIVATE_KEY"],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "ROTATE_OR_REISSUE",
    required: false,
    affectedCapability: "Signing/decrypting Canvas LTI 1.3 JWTs. Checked in priority order: *_B64, then *_PATH (local-dev only), then the raw multiline var.",
    lossImpact: "If lost, a fresh RSA keypair can be generated and re-registered with Canvas (docs/deployment-vercel-supabase.md, \"LTI key setup\") — no historical data depends on the old key, since LTI JWTs are short-lived.",
    rotationImpact: "The new public key must be re-registered with Canvas's Developer Key before launches succeed again; no historical data is invalidated.",
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "src/lib/env/readiness.ts (checkAny); docs/deployment-vercel-supabase.md",
    authoritativeRecoverySourceStatus: AUTHORITATIVE_RECOVERY_SOURCE_NOT_YET_SELECTED,
  },
  {
    name: "LTI_PUBLIC_KEY_B64",
    aliasNames: ["LTI_PUBLIC_KEY_PATH", "LTI_PUBLIC_KEY"],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "ROTATE_OR_REISSUE",
    required: false,
    affectedCapability: "Published at /api/lti/jwks for Canvas's own JWT verification.",
    lossImpact: "Must match LTI_PRIVATE_KEY_B64 — regenerated as a pair.",
    rotationImpact: null,
    recoveryDependency: "LTI_PRIVATE_KEY_B64",
    templatePresenceExpected: true,
    sourceReference: "src/lib/env/readiness.ts (checkAny); docs/deployment-vercel-supabase.md",
    authoritativeRecoverySourceStatus: null,
  },
  {
    // Independent variable, not a true alias — see this module's own
    // "Alias model" doc comment. LTI_TOOL_NAME and LTI_TOOL_DESCRIPTION
    // are two SEPARATE fields (a title and a description), each read
    // with its own independent `||` default in
    // src/app/api/lti/config/route.ts:61,63 — neither is a fallback
    // representation of the other's value. Previously grouped together
    // for register brevity only, which was a modelling error (see
    // register.test.ts's own regression guard for the corrected model).
    name: "LTI_TOOL_NAME",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Cosmetic branding (tool title) shown in /api/lti/config.",
    lossImpact: "Safe default (\"Safe Exam System\") applies if unset.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "src/app/api/lti/config/route.ts:61; .env.example",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "LTI_TOOL_DESCRIPTION",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Cosmetic branding (tool description) shown in /api/lti/config.",
    lossImpact: "Safe default (\"Secure online examination platform with integrity review\") applies if unset.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "src/app/api/lti/config/route.ts:63; .env.example",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "LTI_FRAME_ANCESTORS",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "CSP frame-ancestors allowlist for embedding LTI-compatible pages in an institution's Canvas iframe (src/lib/securityHeaders.ts).",
    lossImpact: "Safe to leave unset — same-origin framing still works; cross-origin Canvas embedding simply stays unavailable until reconfigured.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "src/lib/securityHeaders.ts; .env.example",
    authoritativeRecoverySourceStatus: null,
  },

  // ── Password reset (Resend email) ────────────────────────────────────
  {
    name: "RESEND_API_KEY",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "ROTATE_OR_REISSUE",
    required: false,
    affectedCapability: "Sending password-reset emails. Both RESEND_API_KEY and PASSWORD_RESET_FROM_EMAIL must be set together, or emails are simply not sent (no error exposed to the browser).",
    lossImpact: "A new API key can be issued from the Resend dashboard; no historical data depends on the old key (reset tokens are short-lived and never logged).",
    rotationImpact: "None to historical data — only the operator's own Resend dashboard access is affected.",
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: ".env.example; docs/password-reset-v1.md",
    authoritativeRecoverySourceStatus: AUTHORITATIVE_RECOVERY_SOURCE_NOT_YET_SELECTED,
  },
  {
    name: "PASSWORD_RESET_FROM_EMAIL",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "From-address for password-reset emails; must be on a Resend-verified domain.",
    lossImpact: "Reconstructible — just an email address on a domain already verified with Resend.",
    rotationImpact: null,
    recoveryDependency: "RESEND_API_KEY",
    templatePresenceExpected: true,
    sourceReference: ".env.example; docs/password-reset-v1.md",
    authoritativeRecoverySourceStatus: null,
  },

  // ── Platform admin bootstrap (operator/seed only) ────────────────────
  {
    name: "PLATFORM_ADMIN_EMAIL",
    aliasNames: [],
    category: "OPERATOR_MAINTENANCE_ONLY",
    sensitivity: "NON_SECRET",
    environment: "LOCAL_ONLY",
    runtimeSource: "LOCAL_OPERATOR_ENVIRONMENT",
    recoveryClass: "BOOTSTRAP_ONLY",
    required: false,
    affectedCapability: "prisma/seed.ts creates/updates one PLATFORM_ADMIN account when BOTH this and PLATFORM_ADMIN_PASSWORD are set — never read by any Production request path.",
    lossImpact: "None — the platform admin account, once created, persists in the database independent of this env var; it is only consulted at seed time.",
    rotationImpact: null,
    recoveryDependency: "PLATFORM_ADMIN_PASSWORD",
    templatePresenceExpected: true,
    sourceReference: "prisma/seed.ts:47-71; docs/platform-admin-onboarding.md",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "PLATFORM_ADMIN_PASSWORD",
    aliasNames: [],
    category: "OPERATOR_MAINTENANCE_ONLY",
    sensitivity: "SECRET",
    environment: "LOCAL_ONLY",
    runtimeSource: "LOCAL_OPERATOR_ENVIRONMENT",
    recoveryClass: "BOOTSTRAP_ONLY",
    required: false,
    affectedCapability: "prisma/seed.ts — sets the initial bcrypt-hashed password for the seeded PLATFORM_ADMIN account.",
    lossImpact: "None to existing accounts — the value is used once at seed time to compute a stored bcrypt hash; the raw value itself is never retained by the application afterward. A lost value simply means a NEW seed run needs a NEW value (which then becomes that account's new password, via the seed's own upsert).",
    rotationImpact: "None to other data — this is intentionally a bootstrap-only value, never a long-term credential this register should try to preserve.",
    recoveryDependency: "PLATFORM_ADMIN_EMAIL",
    templatePresenceExpected: true,
    sourceReference: "prisma/seed.ts:47-71; docs/platform-admin-onboarding.md",
    authoritativeRecoverySourceStatus: null,
  },

  // ── Optional AI module ────────────────────────────────────────────────
  {
    name: "ANTHROPIC_API_KEY",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "ROTATE_OR_REISSUE",
    required: false,
    affectedCapability: "AI question generation and AI draft essay marking (both return a safe \"not configured\" error without it).",
    lossImpact: "A new key can be issued from the Anthropic Console; no historical data depends on the old key.",
    rotationImpact: "None to historical data — only the operator's own Anthropic Console access is affected; already-generated AI content in the database is unaffected by rotating the key used to generate future content.",
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "src/lib/env/readiness.ts; .env.example",
    authoritativeRecoverySourceStatus: AUTHORITATIVE_RECOVERY_SOURCE_NOT_YET_SELECTED,
  },

  // ── Geolocation (network evidence, optional) ─────────────────────────
  {
    name: "GEOLOCATION_PROVIDER",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Whether/which IP-based geolocation lookup runs. Defaults to \"none\" — no external call.",
    lossImpact: "Safe default (\"none\") applies if unset.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: ".env.example",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "GEOLOCATION_API_KEY",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "ROTATE_OR_REISSUE",
    required: false,
    affectedCapability: "Higher rate limits for the optional geolocation provider (not required for the ipapi free tier).",
    lossImpact: "A new key can be issued from the provider's dashboard.",
    rotationImpact: null,
    recoveryDependency: "GEOLOCATION_PROVIDER",
    templatePresenceExpected: true,
    sourceReference: ".env.example",
    authoritativeRecoverySourceStatus: AUTHORITATIVE_RECOVERY_SOURCE_NOT_YET_SELECTED,
  },
  {
    name: "GEOLOCATION_TIMEOUT_MS",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Geolocation provider request timeout.",
    lossImpact: "Safe default (2000ms) applies if unset.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: ".env.example",
    authoritativeRecoverySourceStatus: null,
  },

  // ── Evidence storage (Evidence Frames v1) ────────────────────────────
  {
    name: "EVIDENCE_STORAGE_PROVIDER",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Where captured AI-integrity evidence frames are stored. `local_dev` must never be set in Production (no shared filesystem across serverless instances).",
    lossImpact: "Defaults to `local_dev` outside Production — capture simply cannot be enabled for any exam until a real provider is configured; every other feature is unaffected.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "src/lib/env/readiness.ts; docs/deployment-vercel-supabase.md",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "EVIDENCE_STORAGE_BUCKET",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "PROVIDER_LOOKUP",
    required: false,
    affectedCapability: "Which private Supabase Storage bucket evidence frames are written to.",
    lossImpact: "Just a bucket name, visible in the Supabase dashboard once the bucket exists.",
    rotationImpact: null,
    recoveryDependency: "EVIDENCE_STORAGE_PROVIDER",
    templatePresenceExpected: true,
    sourceReference: "src/lib/env/readiness.ts; docs/deployment-vercel-supabase.md",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "SUPABASE_URL",
    aliasNames: ["NEXT_PUBLIC_SUPABASE_URL"],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "PROVIDER_LOOKUP",
    required: false,
    affectedCapability: "Server-side Supabase Storage adapter target for evidence frames (never sent to the browser regardless of which of the two var names holds it).",
    lossImpact: "Visible in the Supabase dashboard — not itself secret.",
    rotationImpact: null,
    recoveryDependency: "EVIDENCE_STORAGE_PROVIDER",
    templatePresenceExpected: true,
    sourceReference: "src/lib/env/readiness.ts; docs/deployment-vercel-supabase.md",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "SUPABASE_SERVICE_ROLE_KEY",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "ROTATE_OR_REISSUE",
    required: false,
    affectedCapability: "Full read/write access to Supabase Storage (bypasses bucket RLS) for the evidence storage adapter. The single highest-sensitivity credential in this register.",
    lossImpact: "Can be regenerated from the Supabase dashboard (Project Settings → API); existing stored objects are unaffected by regenerating this key — only the credential used to reach them changes.",
    rotationImpact: "Every deployment holding the OLD key immediately loses Storage access until updated to the new one — plan a coordinated update + redeploy, not a casual rotation.",
    recoveryDependency: "EVIDENCE_STORAGE_PROVIDER",
    templatePresenceExpected: true,
    sourceReference: "src/lib/env/readiness.ts; docs/deployment-vercel-supabase.md",
    authoritativeRecoverySourceStatus: AUTHORITATIVE_RECOVERY_SOURCE_NOT_YET_SELECTED,
  },
  {
    name: "EVIDENCE_RETENTION_DAYS",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Manual evidence-retention runner window (npm run evidence:retention).",
    lossImpact: "Safe default (90 days) applies if unset.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "docs/production-environment-register.md; docs/tether-evidence-retention-plan.md",
    authoritativeRecoverySourceStatus: null,
  },

  // ── Secure-client / SEB config encryption ────────────────────────────
  {
    name: "TETHER_SEB_KEY_ENCRYPTION_KEYS_JSON",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "PRESERVE_EXACT_VALUE",
    required: false,
    affectedCapability: "AES-256 encryption/decryption of stored SEB (Safe Exam Browser) Browser Exam Key / Config Key material (src/lib/secureClient/sebKeyEncryption.ts). Structured JSON secret material — one 64-hex-char AES-256 key per retired-or-active key id.",
    lossImpact: "Missing or malformed fails closed (adding a new SEB key throws; decrypting any existing key returns null — no runtime-generated fallback). If a retired key id's material is permanently lost, every SEB key ever encrypted under that id becomes permanently undecipherable — this is why every retired key id must be KEPT in this JSON map, never removed until nothing is encrypted under it any more.",
    rotationImpact: "Adding a NEW key id is safe (does not affect existing ciphertext). Removing an id before every value encrypted under it has been re-encrypted or deleted permanently destroys access to that data.",
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "src/lib/secureClient/sebKeyEncryption.ts:13-26; .env.example",
    authoritativeRecoverySourceStatus: AUTHORITATIVE_RECOVERY_SOURCE_NOT_YET_SELECTED,
  },
  {
    name: "TETHER_SEB_KEY_ENCRYPTION_ACTIVE_KEY_ID",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Which key id in TETHER_SEB_KEY_ENCRYPTION_KEYS_JSON new SEB keys are encrypted with.",
    lossImpact: "Must be a key id genuinely present in TETHER_SEB_KEY_ENCRYPTION_KEYS_JSON — reconstructible once that JSON's own key ids are known.",
    rotationImpact: null,
    recoveryDependency: "TETHER_SEB_KEY_ENCRYPTION_KEYS_JSON",
    templatePresenceExpected: true,
    sourceReference: "src/lib/secureClient/sebKeyEncryption.ts; .env.example",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "TETHER_SEB_EXPERIMENTAL_ENABLED",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Feature flag gating both SEB_OPTIONAL and SEB_REQUIRED experimental delivery modes.",
    lossImpact: "Safe default (false) applies if unset.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: ".env.example",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "TETHER_SEB_REQUIRED_ALLOWED_INSTITUTION_SLUGS",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Institution allowlist for SEB_REQUIRED, ignored unless TETHER_SEB_EXPERIMENTAL_ENABLED=true.",
    lossImpact: "Reconstructible from institutional records of which slugs were approved.",
    rotationImpact: null,
    recoveryDependency: "TETHER_SEB_EXPERIMENTAL_ENABLED",
    templatePresenceExpected: true,
    sourceReference: ".env.example",
    authoritativeRecoverySourceStatus: null,
  },

  // ── Tether secure-launch signing ─────────────────────────────────────
  {
    name: "TETHER_SECURE_CLIENT_SIGNING_PRIVATE_KEY",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "ROTATE_OR_REISSUE",
    required: false,
    affectedCapability: "Signs Tether Secure Browser launch manifests and attestation challenges (src/lib/secureClientRunner.ts). Required if this deployment supports Tether at all.",
    lossImpact: "A freshly generated Ed25519 keypair can be issued (see docs/secure-launch-signing-key-runbook.md). No long-term historical data depends on the old key's exact value — manifest/challenge TTLs are short (120 seconds for challenges) — but see rotationImpact for the blast radius of a rotation.",
    rotationImpact: "Every manifest/challenge issued under the OLD key that has not yet been consumed becomes permanently unverifiable the instant the key changes — there is currently no overlapping-verification-window mechanism (see docs/secure-launch-signing-key-runbook.md, \"The gap\"). Any student mid-launch at the exact moment of rotation gets a hard failure, not a graceful fallback. Bounded to the in-flight window (short TTLs), but real.",
    recoveryDependency: "TETHER_SECURE_CLIENT_SIGNING_PUBLIC_KEY",
    templatePresenceExpected: true,
    sourceReference: "docs/secure-launch-signing-key-runbook.md; src/lib/env/readiness.ts",
    authoritativeRecoverySourceStatus: AUTHORITATIVE_RECOVERY_SOURCE_NOT_YET_SELECTED,
  },
  {
    name: "TETHER_SECURE_CLIENT_SIGNING_PUBLIC_KEY",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "ROTATE_OR_REISSUE",
    required: false,
    affectedCapability: "Verifies signatures made by TETHER_SECURE_CLIENT_SIGNING_PRIVATE_KEY.",
    lossImpact: "Must exactly match the private key — regenerated as a pair, never independently.",
    rotationImpact: "See TETHER_SECURE_CLIENT_SIGNING_PRIVATE_KEY — the two must always change together.",
    recoveryDependency: "TETHER_SECURE_CLIENT_SIGNING_PRIVATE_KEY",
    templatePresenceExpected: true,
    sourceReference: "docs/secure-launch-signing-key-runbook.md; src/lib/env/readiness.ts",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "TETHER_SECURE_CLIENT_SIGNING_KEY_ID",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Diagnostic label embedded in issued manifests/challenges — not currently used to select which public key verifies a signature (see docs/secure-launch-signing-key-runbook.md, \"the gap\").",
    lossImpact: "Defaults to \"dev-key-1\" if unset.",
    rotationImpact: null,
    recoveryDependency: "TETHER_SECURE_CLIENT_SIGNING_PRIVATE_KEY",
    templatePresenceExpected: true,
    sourceReference: "docs/secure-launch-signing-key-runbook.md; .env.example",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "TETHER_CLIENT_REQUIRED_DISABLED",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Emergency kill-switch for TETHER_CLIENT_REQUIRED delivery mode.",
    lossImpact: "Safe default (false) applies if unset.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: ".env.example",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "TETHER_CLIENT_OPTIONAL_ENABLED",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "TETHER_CLIENT_OPTIONAL delivery-mode availability toggle.",
    lossImpact: "Safe default applies if unset — see docs/production-environment-register.md.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "docs/production-environment-register.md — NOT currently present in .env.example (drift; corrected by this pass)",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "TETHER_SECURE_CLIENT_BYPASS_ENABLED",
    aliasNames: [],
    category: "LOCAL_DEVELOPMENT_ONLY",
    sensitivity: "NON_SECRET",
    environment: "NOT_APPLICABLE",
    runtimeSource: "LOCAL_OPERATOR_ENVIRONMENT",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Development/Preview-only bypass allowing ordinary-browser exam access despite TETHER_CLIENT_REQUIRED. Never available in Production regardless of value.",
    lossImpact: "Safe default (false) applies if unset.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: ".env.example",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "TETHER_SECURE_CLIENT_BYPASS_ALLOWED_INSTITUTION_SLUGS",
    aliasNames: [],
    category: "LOCAL_DEVELOPMENT_ONLY",
    sensitivity: "NON_SECRET",
    environment: "NOT_APPLICABLE",
    runtimeSource: "LOCAL_OPERATOR_ENVIRONMENT",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Institution allowlist for the development bypass above.",
    lossImpact: "Reconstructible from institutional records.",
    rotationImpact: null,
    recoveryDependency: "TETHER_SECURE_CLIENT_BYPASS_ENABLED",
    templatePresenceExpected: true,
    sourceReference: ".env.example",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "TETHER_MOCK_SECURE_CLIENT_ENABLED",
    aliasNames: [],
    category: "LOCAL_DEVELOPMENT_ONLY",
    sensitivity: "NON_SECRET",
    environment: "NOT_APPLICABLE",
    runtimeSource: "LOCAL_OPERATOR_ENVIRONMENT",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Enables the non-cryptographic mock secure-client dev simulator. Actively detected as a dangerous combination if true in Production (MOCK_SECURE_CLIENT_ENABLED_IN_PRODUCTION).",
    lossImpact: "Safe default (unset/false) — must never be true in Production.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "docs/production-environment-register.md; src/lib/env/readiness.ts (detectDangerousEnvCombinations) — NOT currently present in .env.example (drift; corrected by this pass)",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "TETHER_MOCK_CLIENT_ALLOWED_INSTITUTION_SLUGS",
    aliasNames: [],
    category: "LOCAL_DEVELOPMENT_ONLY",
    sensitivity: "NON_SECRET",
    environment: "NOT_APPLICABLE",
    runtimeSource: "LOCAL_OPERATOR_ENVIRONMENT",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Institution allowlist for the mock secure-client simulator.",
    lossImpact: "Reconstructible from institutional records.",
    rotationImpact: null,
    recoveryDependency: "TETHER_MOCK_SECURE_CLIENT_ENABLED",
    templatePresenceExpected: true,
    sourceReference: "docs/production-environment-register.md — NOT currently present in .env.example (drift; corrected by this pass)",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "TETHER_DIAGNOSTIC_LOGGING_ENABLED",
    aliasNames: [],
    category: "LOCAL_DEVELOPMENT_ONLY",
    sensitivity: "NON_SECRET",
    environment: "NOT_APPLICABLE",
    runtimeSource: "LOCAL_OPERATOR_ENVIRONMENT",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Verbose Tether launch-pipeline tracing. Structurally impossible in Production regardless of this flag's value (src/lib/tetherDiagnosticLog.ts hardcodes a non-production precondition).",
    lossImpact: "Safe default (unset/false).",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "docs/production-environment-register.md; src/lib/tetherDiagnosticLog.ts — NOT currently present in .env.example (drift; corrected by this pass)",
    authoritativeRecoverySourceStatus: null,
  },

  // ── Tether System Check / Attestation / Recovery-Resilience tuning ───
  {
    name: "TETHER_SYSTEM_CHECK_MODE",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "OFF/WARN/REQUIRE gating for the Tether System Check and Exam Readiness feature.",
    lossImpact: "Safe default (WARN) applies if unset or malformed.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: ".env.example; docs/tether-system-check-v1.md",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "TETHER_SYSTEM_CHECK_VALIDITY_HOURS",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "How long a stored system-check result stays current.",
    lossImpact: "Safe default (24 hours) applies if unset or non-positive.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: ".env.example",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "TETHER_MINIMUM_SUPPORTED_VERSION",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Minimum Tether Secure Browser client version a system check reports as supported.",
    lossImpact: "Safe default (\"1.5.0\") applies if unset.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: ".env.example; docs/tether-system-check-v1.md",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "TETHER_EXAM_ATTESTATION_MODE",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "LEGACY/DUAL/V2_REQUIRED attestation-requirement mode for newly created secure-client sessions.",
    lossImpact: "Safe default (LEGACY) applies if unset or unrecognised; already-created sessions are unaffected either way (snapshotted at session-creation time, never re-read).",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: ".env.example",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "TETHER_MAX_ACTIVE_INSTALLATIONS_PER_USER",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Multi-device installation registration limit.",
    lossImpact: "Safe default (2) applies if unset; clamped to [1,5].",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: ".env.example",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "TETHER_OFFLINE_CONTINUE_MINUTES",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "How long a session stays trusted after its heartbeat goes overdue before a fresh crash-recovery is required.",
    lossImpact: "Safe default (10 minutes) applies if unset; clamped to [2,30].",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: ".env.example",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "TETHER_AUTOSAVE_RETRY_MAX_SECONDS",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Client-side autosave retry backoff ceiling.",
    lossImpact: "Safe default (60 seconds) applies if unset; clamped to [10,300].",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: ".env.example",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "TETHER_PENDING_SAVE_RETENTION_HOURS",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "How long an unsent locally-queued answer draft may remain in browser IndexedDB.",
    lossImpact: "Safe default (72 hours) applies if unset; clamped to [1,168].",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: ".env.example",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "TETHER_HEARTBEAT_INTERVAL_SECONDS",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Default heartbeat cadence suggested before a per-exam policy is known.",
    lossImpact: "Safe default (30 seconds) applies if unset; clamped to [15,120].",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: ".env.example",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "TETHER_SECURE_LAUNCH_CONSUME_TRANSACTION_TIMEOUT_MS",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Interactive-transaction timeout for launch-manifest consume.",
    lossImpact: "Safe default with min/max clamps applies if unset.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "docs/production-environment-register.md — NOT currently present in .env.example (drift; corrected by this pass)",
    authoritativeRecoverySourceStatus: null,
  },
  // Four INDEPENDENT lockdown-capability toggles — see this module's own
  // "Alias model" doc comment. Each is read at its own line in
  // src/lib/tetherLockdownConfig.ts, with its own independent default;
  // none is a fallback representation of another's value. Previously
  // grouped as one entry via aliasNames for register brevity, which was
  // a modelling error — deleting one from .env.example while the other
  // three remained present would have gone undetected, since the old
  // "any name present satisfies the entry" check only required ONE of
  // the four to exist. Corrected: four separate entries, each
  // independently checked for template presence (see
  // register.test.ts's own regression guard).
  {
    name: "TETHER_BLOCK_DEBUG_TOOLS",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Lockdown toggle: governs Visual Studio, Process Explorer, and other debug-tool detection/blocking on the Tether native client.",
    lossImpact: "Safe default (false — detect-only, higher false-positive risk) applies if unset.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "src/lib/tetherLockdownConfig.ts:79; .env.example",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "TETHER_BLOCK_REMOTE_CONTROL",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Lockdown toggle: governs every REMOTE_CONTROL-class tool's detection/blocking on the Tether native client.",
    lossImpact: "Safe default (true) applies if unset.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "src/lib/tetherLockdownConfig.ts:77; .env.example",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "TETHER_BLOCK_SCREEN_CAPTURE_TOOLS",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Lockdown toggle: governs OBS and other dedicated screen-capture tool detection/blocking on the Tether native client.",
    lossImpact: "Safe default (true) applies if unset.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "src/lib/tetherLockdownConfig.ts:78; .env.example",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "TETHER_BLOCK_VIRTUAL_MACHINES",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Lockdown toggle: governs Hyper-V console, VMware, and other virtual-machine detection/blocking on the Tether native client.",
    lossImpact: "Safe default (false) applies if unset.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "src/lib/tetherLockdownConfig.ts:80; .env.example",
    authoritativeRecoverySourceStatus: null,
  },

  // ── Tether release / distribution metadata (NAMES only — see branding freeze) ──
  {
    name: "TETHER_INSTALLER_DOWNLOAD_URL",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Real, published Tether Secure Browser installer URL — absent means downloads stay disabled.",
    lossImpact: "Reconstructible once the installer's hosting location is known — see docs/backup-and-disaster-recovery-runbook-v1.md Section 14 for the currently-unreconciled release-version state this depends on.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "src/lib/tetherReleaseMetadata.ts:78; docs/production-environment-register.md — NOT currently present in .env.example (drift; corrected by this pass)",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "TETHER_RELEASE_STATUS",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "INTERNAL (default) / PILOT / GENERAL_AVAILABILITY release status.",
    lossImpact: "Safe default (INTERNAL) applies if unset.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "src/lib/tetherReleaseMetadata.ts:98; docs/production-environment-register.md — NOT currently present in .env.example (drift; corrected by this pass)",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "TETHER_RELEASE_NOTES_URL",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Optional release-notes link.",
    lossImpact: "Optional — no functional loss if unset.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "src/lib/tetherReleaseMetadata.ts:104; docs/production-environment-register.md — NOT currently present in .env.example (drift; corrected by this pass)",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "TETHER_SUPPORT_CONTACT",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Deployment-wide support contact string (src/lib/institutionSupportContact.ts).",
    lossImpact: "Optional — no functional loss if unset.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "docs/production-environment-register.md — NOT currently present in .env.example (drift; corrected by this pass)",
    authoritativeRecoverySourceStatus: null,
  },

  // ── Client-consumed / misc toggles ────────────────────────────────────
  {
    name: "NEXT_PUBLIC_TETHER_PHONE_CALIBRATION_ENABLED",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Client-side phone-camera calibration UI feature flag (src/app/student/exams/[id]/page.tsx). The one genuinely browser-consumed NEXT_PUBLIC_* variable found in this codebase — deliberately non-secret, appropriate use of the convention.",
    lossImpact: "Safe default applies if unset.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "src/app/student/exams/[id]/page.tsx:3768; src/lib/cameraIntegrityDetection.ts:170",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "TETHER_TIMING_HEADERS_ENABLED",
    aliasNames: [],
    category: "OPTIONAL_PRODUCTION_RUNTIME",
    sensitivity: "NON_SECRET",
    environment: "PRODUCTION_AND_PREVIEW",
    runtimeSource: "VERCEL_ENVIRONMENT_VARIABLE",
    recoveryClass: "RECONSTRUCT_CONFIGURATION",
    required: false,
    affectedCapability: "Gates exposing Server-Timing response headers on a small set of routes — off by default everywhere including Production.",
    lossImpact: "Safe default (off) applies if unset.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: true,
    sourceReference: "src/lib/serverTiming.ts:86; src/app/api/submissions/[id]/save-and-navigate/route.ts:215 — NOT currently present in .env.example (drift; corrected by this pass)",
    authoritativeRecoverySourceStatus: null,
  },

  // ── Superseded / not actually read (kept so drift is surfaced, not hidden) ──
  // SUPABASE_ACCESS_TOKEN and SUPABASE_DB_PASSWORD are two DIFFERENT
  // historical/deprecated credentials from an earlier, superseded
  // backup-adapter design — not alternate representations of one
  // logical secret (see this module's own "Alias model" doc comment).
  // Previously grouped via aliasNames for register brevity, which was a
  // modelling error; corrected to two independent entries.
  {
    name: "SUPABASE_ACCESS_TOKEN",
    aliasNames: [],
    category: "DEPRECATED_DOCUMENTED_NOT_USED",
    sensitivity: "SECRET",
    environment: "NOT_APPLICABLE",
    runtimeSource: "NOT_APPLICABLE",
    recoveryClass: null,
    required: false,
    affectedCapability: "None — an earlier design of the Supabase-managed backup adapter would have required this; the shipped design (scripts/backupCreation/supabaseCliExecutor.ts) explicitly does not read it, using a passwordless --db-url + PGPASSWORD (derived from the already-parsed source connection) instead. Referenced only inside supabaseCliExecutor.test.ts, purely for defensive test-environment isolation (saving/restoring an ambient value that might otherwise leak between tests) — never read by any real script.",
    lossImpact: "Not applicable — nothing reads this name.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: false,
    sourceReference: "scripts/backupCreation/supabaseCliExecutor.ts:57-62 (explicit doc-comment statement that neither this nor SUPABASE_DB_PASSWORD is required)",
    authoritativeRecoverySourceStatus: null,
    notes: "Kept here precisely so a future reader who sees this name in test-isolation code does not mistake it for live configuration.",
  },
  {
    name: "SUPABASE_DB_PASSWORD",
    aliasNames: [],
    category: "DEPRECATED_DOCUMENTED_NOT_USED",
    sensitivity: "SECRET",
    environment: "NOT_APPLICABLE",
    runtimeSource: "NOT_APPLICABLE",
    recoveryClass: null,
    required: false,
    affectedCapability: "None — same superseded backup-adapter design as SUPABASE_ACCESS_TOKEN, but historically a distinct credential (a database password, not an API access token) — never an alternate representation of it. Referenced only inside supabaseCliExecutor.test.ts, purely for defensive test-environment isolation — never read by any real script.",
    lossImpact: "Not applicable — nothing reads this name.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: false,
    sourceReference: "scripts/backupCreation/supabaseCliExecutor.ts:57-62 (explicit doc-comment statement that neither this nor SUPABASE_ACCESS_TOKEN is required)",
    authoritativeRecoverySourceStatus: null,
    notes: "Kept here precisely so a future reader who sees this name in test-isolation code does not mistake it for live configuration.",
  },

  // ── Backup operator tooling (see docs/database-backup-operations-v1.md) ──
  {
    name: "BACKUP_SOURCE_DATABASE_URL",
    aliasNames: [],
    category: "OPERATOR_MAINTENANCE_ONLY",
    sensitivity: "SECRET",
    environment: "NOT_APPLICABLE",
    runtimeSource: "LOCAL_OPERATOR_ENVIRONMENT",
    recoveryClass: "ROTATE_OR_REISSUE",
    required: false,
    affectedCapability: "`npm run backup:create` only — never read by the running application. Deliberately separate from DATABASE_URL so a backup run never depends on the app's own pooled connection string.",
    lossImpact: "Falls back to DATABASE_URL if unset — same recovery path as that entry.",
    rotationImpact: "See DATABASE_URL.",
    recoveryDependency: "DATABASE_URL",
    templatePresenceExpected: true,
    sourceReference: "scripts/create-database-backup.ts; docs/database-backup-operations-v1.md",
    authoritativeRecoverySourceStatus: AUTHORITATIVE_RECOVERY_SOURCE_NOT_YET_SELECTED,
  },

  // ── Evidence archive (architecture exists; NOT provisioned) ──────────
  {
    name: "ARCHIVE_STORAGE_PROVIDER",
    aliasNames: [],
    category: "FUTURE_NOT_PROVISIONED",
    sensitivity: "NON_SECRET",
    environment: "NOT_APPLICABLE",
    runtimeSource: "NOT_YET_PROVISIONED",
    recoveryClass: "FUTURE_NOT_PROVISIONED",
    required: false,
    affectedCapability: "npm run evidence:archive — no archive Supabase project has been provisioned; this tool is not used against any real destination yet.",
    lossImpact: "Not applicable — nothing is currently configured to lose.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: false,
    sourceReference: "src/lib/evidenceArchiveStorage.ts; docs/tether-evidence-archive-plan.md",
    authoritativeRecoverySourceStatus: null,
    notes: "Deliberately NOT added to .env.example while the architecture remains unprovisioned — see docs/tether-evidence-archive-plan.md, \"What was deliberately NOT done in this pass.\"",
  },
  {
    name: "ARCHIVE_SUPABASE_URL",
    aliasNames: [],
    category: "FUTURE_NOT_PROVISIONED",
    sensitivity: "NON_SECRET",
    environment: "NOT_APPLICABLE",
    runtimeSource: "NOT_YET_PROVISIONED",
    recoveryClass: "FUTURE_NOT_PROVISIONED",
    required: false,
    affectedCapability: "Same as ARCHIVE_STORAGE_PROVIDER.",
    lossImpact: "Not applicable.",
    rotationImpact: null,
    recoveryDependency: "ARCHIVE_STORAGE_PROVIDER",
    templatePresenceExpected: false,
    sourceReference: "src/lib/evidenceArchiveStorage.ts; docs/tether-evidence-archive-plan.md",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "ARCHIVE_SUPABASE_SERVICE_ROLE_KEY",
    aliasNames: [],
    category: "FUTURE_NOT_PROVISIONED",
    sensitivity: "SECRET",
    environment: "NOT_APPLICABLE",
    runtimeSource: "NOT_YET_PROVISIONED",
    recoveryClass: "FUTURE_NOT_PROVISIONED",
    required: false,
    affectedCapability: "Same as ARCHIVE_STORAGE_PROVIDER. Must never be the same value as SUPABASE_SERVICE_ROLE_KEY once provisioned — a genuinely separate project's own key.",
    lossImpact: "Not applicable.",
    rotationImpact: null,
    recoveryDependency: "ARCHIVE_STORAGE_PROVIDER",
    templatePresenceExpected: false,
    sourceReference: "src/lib/evidenceArchiveStorage.ts; docs/tether-evidence-archive-plan.md",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "ARCHIVE_STORAGE_BUCKET",
    aliasNames: [],
    category: "FUTURE_NOT_PROVISIONED",
    sensitivity: "NON_SECRET",
    environment: "NOT_APPLICABLE",
    runtimeSource: "NOT_YET_PROVISIONED",
    recoveryClass: "FUTURE_NOT_PROVISIONED",
    required: false,
    affectedCapability: "Same as ARCHIVE_STORAGE_PROVIDER.",
    lossImpact: "Not applicable.",
    rotationImpact: null,
    recoveryDependency: "ARCHIVE_STORAGE_PROVIDER",
    templatePresenceExpected: false,
    sourceReference: "src/lib/evidenceArchiveStorage.ts; docs/tether-evidence-archive-plan.md",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "ARCHIVE_SOURCE_ENVIRONMENT",
    aliasNames: [],
    category: "FUTURE_NOT_PROVISIONED",
    sensitivity: "NON_SECRET",
    environment: "NOT_APPLICABLE",
    runtimeSource: "NOT_YET_PROVISIONED",
    recoveryClass: "FUTURE_NOT_PROVISIONED",
    required: false,
    affectedCapability: "Manifest metadata only, once provisioned — has zero influence on the archive/restore production-safety guard (a deliberate security correction — see docs/tether-evidence-archive-plan.md).",
    lossImpact: "Not applicable.",
    rotationImpact: null,
    recoveryDependency: "ARCHIVE_STORAGE_PROVIDER",
    templatePresenceExpected: false,
    sourceReference: "src/lib/evidenceArchive.ts; docs/tether-evidence-archive-plan.md",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "ARCHIVE_EXPECTED_PRIMARY_PROJECT_REF",
    aliasNames: [],
    category: "FUTURE_NOT_PROVISIONED",
    sensitivity: "NON_SECRET",
    environment: "NOT_APPLICABLE",
    runtimeSource: "NOT_YET_PROVISIONED",
    recoveryClass: "FUTURE_NOT_PROVISIONED",
    required: false,
    affectedCapability: "Required, once provisioned, for the project-separation guard (assertSupabaseArchiveOperationSafe) that fails closed if the archive project would ever resolve to the same Supabase project as the primary.",
    lossImpact: "Not applicable.",
    rotationImpact: null,
    recoveryDependency: "ARCHIVE_STORAGE_PROVIDER",
    templatePresenceExpected: false,
    sourceReference: "src/lib/evidenceArchive.ts; docs/tether-evidence-archive-plan.md",
    authoritativeRecoverySourceStatus: null,
  },

  // ── Provider / platform supplied (never operator-set) ────────────────
  {
    name: "NODE_ENV",
    aliasNames: [],
    category: "PROVIDER_PLATFORM_SUPPLIED",
    sensitivity: "NON_SECRET",
    environment: "ALL_DEPLOYMENTS",
    runtimeSource: "PROVIDER_SUPPLIED_AT_RUNTIME",
    recoveryClass: null,
    required: true,
    affectedCapability: "Standard Node.js environment marker, consulted throughout the codebase (dev/production branching).",
    lossImpact: "Not applicable — set automatically by the runtime/build tooling, never by an operator.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: false,
    sourceReference: "docs/production-environment-register.md",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "VERCEL_ENV",
    aliasNames: [],
    category: "PROVIDER_PLATFORM_SUPPLIED",
    sensitivity: "NON_SECRET",
    environment: "ALL_DEPLOYMENTS",
    runtimeSource: "PROVIDER_SUPPLIED_AT_RUNTIME",
    recoveryClass: null,
    required: true,
    affectedCapability: "production / preview / development — the actual Production-detection signal (src/lib/secureClientAvailability.ts's deploymentEnvironment()), deliberately NOT NODE_ENV (which is \"production\" for both Preview and Production builds on Vercel).",
    lossImpact: "Not applicable — set automatically by Vercel.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: false,
    sourceReference: "src/lib/secureClientAvailability.ts; docs/production-environment-register.md",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "VERCEL_GIT_COMMIT_SHA",
    aliasNames: ["GIT_COMMIT_SHA"],
    category: "PROVIDER_PLATFORM_SUPPLIED",
    sensitivity: "NON_SECRET",
    environment: "ALL_DEPLOYMENTS",
    runtimeSource: "BUILD_TOOLING_SUPPLIED",
    recoveryClass: null,
    required: false,
    affectedCapability: "Build commit SHA surfaced by GET /api/version — informational only.",
    lossImpact: "Not applicable — supplied automatically by Vercel's build environment.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: false,
    sourceReference: "docs/production-environment-register.md",
    authoritativeRecoverySourceStatus: null,
  },
  {
    name: "VERCEL_BUILD_TIMESTAMP",
    aliasNames: [],
    category: "PROVIDER_PLATFORM_SUPPLIED",
    sensitivity: "NON_SECRET",
    environment: "ALL_DEPLOYMENTS",
    runtimeSource: "BUILD_TOOLING_SUPPLIED",
    recoveryClass: null,
    required: false,
    affectedCapability: "Build timestamp surfaced by GET /api/version — informational only.",
    lossImpact: "Not applicable.",
    rotationImpact: null,
    recoveryDependency: null,
    templatePresenceExpected: false,
    sourceReference: "docs/production-environment-register.md",
    authoritativeRecoverySourceStatus: null,
  },
] as const;

/** Convenience lookup — throws if the name (or one of its known aliases) is not registered, so a typo is caught immediately rather than silently returning undefined. */
export function getConfigRecoveryEntry(name: string): ConfigRecoveryEntry {
  const entry = CONFIGURATION_RECOVERY_REGISTER.find((e) => e.name === name || e.aliasNames.includes(name));
  if (!entry) throw new Error(`No configuration recovery register entry for "${name}".`);
  return entry;
}
