-- Institution Entitlement & Access Control v1 (additive) — see
-- docs/institution-entitlement-v1.md and
-- prisma/schema.prisma's InstitutionEntitlement doc comment for full
-- field documentation.
--
-- Generated by comparing against:
--   npx prisma migrate diff --from-schema=<schema at commit d03d146bc367ac032b46e459fd2eba7f551530fd> --to-schema=prisma/schema.prisma --script
-- (a genuine schema-to-schema diff, not --from-empty — this project has
-- no prisma/migrations history to diff from-empty against safely, and a
-- direct two-schema diff produces exactly the real delta with no
-- database connection required to generate it).
--
-- Hardening pass (2026-09-16) — this file now contains BOTH the
-- additive schema change AND its SQL backfill, applied together as one
-- script (matching this repository's real deployment path: manual
-- application via the Supabase SQL Editor — see the Migration
-- convention section of docs/migration-ledger.md). Earlier guidance in
-- this file's own header said prisma/seed.ts was sufficient as the
-- production backfill mechanism; that was wrong for THIS project
-- specifically, because prisma/seed.ts is never automatically run
-- against Preview/Production the way `db push`+seed is for the
-- disposable release-validate database — it is a dev/local convenience
-- only here. See "What happens under each scenario" near the bottom of
-- this file for the exact, now-corrected behaviour.
--
-- Additive only — TWO new enums and ONE new table, plus its indexes and
-- foreign key, PLUS an INSERT ... SELECT backfill that only ever adds
-- rows (never updates or deletes an existing one). No existing table,
-- column, constraint, row, enum value, or index is changed, removed, or
-- renamed. Institution.plan and Institution.active are left completely
-- untouched by this migration — see docs/institution-entitlement-v1.md,
-- "Legacy field handling".
--
-- New enums: InstitutionAccessType (INTERNAL/TRIAL/FREE/PAID),
-- InstitutionEntitlementStatus (ACTIVE/SUSPENDED/EXPIRED/GRACE).
--
-- New table: InstitutionEntitlement — one row per institution
-- (UNIQUE institutionId, ON DELETE CASCADE from Institution). Every
-- column is either NOT NULL with a safe default (the five
-- *Enabled boolean feature flags, all DEFAULT true — see the design
-- doc's "why true" rationale) or nullable-meaning-unrestricted
-- (startsAt/endsAt/graceEndsAt/candidateLimit/attemptLimit/internalNotes
-- — NULL means "no limit"/"not restricted", never a magic sentinel like
-- -1).
--
-- Read-only pre-check (run first, in the Supabase SQL Editor):
--   SELECT table_name FROM information_schema.tables
--   WHERE table_schema = 'public' AND table_name = 'InstitutionEntitlement';
--   -- Expected: no rows (this migration has not yet been applied).
--
-- Requires pgcrypto's gen_random_uuid() for the backfill's generated
-- row ids (enabled by default on every Supabase project; built into
-- PostgreSQL core since v13 on any other Postgres). If this errors with
-- "function gen_random_uuid() does not exist", run
-- `CREATE EXTENSION IF NOT EXISTS pgcrypto;` first — read-only/no-op if
-- already enabled.

-- CreateEnum
CREATE TYPE "InstitutionAccessType" AS ENUM ('INTERNAL', 'TRIAL', 'FREE', 'PAID');

-- CreateEnum
CREATE TYPE "InstitutionEntitlementStatus" AS ENUM ('ACTIVE', 'SUSPENDED', 'EXPIRED', 'GRACE');

-- CreateTable
CREATE TABLE "InstitutionEntitlement" (
    "id" TEXT NOT NULL,
    "institutionId" TEXT NOT NULL,
    "accessType" "InstitutionAccessType" NOT NULL,
    "status" "InstitutionEntitlementStatus" NOT NULL,
    "startsAt" TIMESTAMP(3),
    "endsAt" TIMESTAMP(3),
    "graceEndsAt" TIMESTAMP(3),
    "candidateLimit" INTEGER,
    "attemptLimit" INTEGER,
    "secureBrowserEnabled" BOOLEAN NOT NULL DEFAULT true,
    "aiBrainstormingEnabled" BOOLEAN NOT NULL DEFAULT true,
    "aiMarkingEnabled" BOOLEAN NOT NULL DEFAULT true,
    "analyticsEnabled" BOOLEAN NOT NULL DEFAULT true,
    "advancedReportingEnabled" BOOLEAN NOT NULL DEFAULT true,
    "internalNotes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "InstitutionEntitlement_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "InstitutionEntitlement_institutionId_key" ON "InstitutionEntitlement"("institutionId");

-- CreateIndex
CREATE INDEX "InstitutionEntitlement_accessType_idx" ON "InstitutionEntitlement"("accessType");

-- CreateIndex
CREATE INDEX "InstitutionEntitlement_status_idx" ON "InstitutionEntitlement"("status");

-- AddForeignKey
ALTER TABLE "InstitutionEntitlement" ADD CONSTRAINT "InstitutionEntitlement_institutionId_fkey" FOREIGN KEY ("institutionId") REFERENCES "Institution"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ---------------------------------------------------------------------
-- Backfill — every existing institution gets an explicit row, mapped
-- conservatively from its own legacy plan/active fields, EXACTLY as
-- decided and documented in src/lib/institutionEntitlement.ts's
-- mapLegacyInstitutionToEntitlementInput() and
-- docs/institution-entitlement-v1.md's "Migration & backfill":
--   plan = 'pilot'  -> accessType TRIAL   |  any other plan -> PAID
--   active = true   -> status ACTIVE      |  active = false -> SUSPENDED
--   startsAt/endsAt/graceEndsAt: always NULL (never invents an expiry)
--   candidateLimit/attemptLimit: always NULL (never imposes a limit)
--   every *Enabled flag: true (preserves existing capability access)
--
-- The LEFT JOIN ... WHERE e."id" IS NULL guard means this INSERT only
-- ever touches an institution that does NOT already have a row — safe
-- to re-run (a second run inserts zero rows, since every institution
-- from the first run now has one) and it can NEVER overwrite a row
-- Platform Admin has already edited via
-- PUT /api/platform/institutions/[id]/entitlement.
-- ---------------------------------------------------------------------
INSERT INTO "InstitutionEntitlement" (
    "id", "institutionId", "accessType", "status",
    "startsAt", "endsAt", "graceEndsAt",
    "candidateLimit", "attemptLimit",
    "secureBrowserEnabled", "aiBrainstormingEnabled", "aiMarkingEnabled", "analyticsEnabled", "advancedReportingEnabled",
    "internalNotes", "createdAt", "updatedAt"
)
SELECT
    gen_random_uuid()::text,
    i."id",
    CASE WHEN lower(trim(i."plan")) = 'pilot' THEN 'TRIAL' ELSE 'PAID' END::"InstitutionAccessType",
    CASE WHEN i."active" THEN 'ACTIVE' ELSE 'SUSPENDED' END::"InstitutionEntitlementStatus",
    NULL, NULL, NULL,
    NULL, NULL,
    true, true, true, true, true,
    'Migrated from legacy plan="' || i."plan" || '", active=' || i."active" || ' by the Institution Entitlement & Access Control v1 SQL backfill.',
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM "Institution" i
LEFT JOIN "InstitutionEntitlement" e ON e."institutionId" = i."id"
WHERE e."id" IS NULL;

-- Post-apply verification (read-only):
--   SELECT column_name FROM information_schema.columns
--   WHERE table_name = 'InstitutionEntitlement' ORDER BY ordinal_position;
--   -- Expected: the 17 columns listed above.
--
--   SELECT indexname FROM pg_indexes WHERE tablename = 'InstitutionEntitlement';
--   -- Expected: InstitutionEntitlement_pkey, _institutionId_key, _accessType_idx, _status_idx.
--
--   SELECT count(*) FROM "InstitutionEntitlement";
--   -- Expected: equal to the current row count of "Institution" (every
--   -- institution now has exactly one row — UNIQUE institutionId
--   -- guarantees no institution has more than one).
--
--   SELECT count(*) FROM "Institution" i
--   LEFT JOIN "InstitutionEntitlement" e ON e."institutionId" = i."id"
--   WHERE e."id" IS NULL;
--   -- Expected: 0 (no institution left without a row).
--
--   SELECT i."name", i."plan", i."active", e."accessType", e."status"
--   FROM "Institution" i JOIN "InstitutionEntitlement" e ON e."institutionId" = i."id"
--   ORDER BY i."createdAt";
--   -- Spot-check: every plan='pilot' row maps to TRIAL, every other
--   -- plan maps to PAID; every active=true maps to ACTIVE, every
--   -- active=false maps to SUSPENDED.

-- ---------------------------------------------------------------------
-- What happens under each scenario (docs/institution-entitlement-v1.md
-- cross-references this section directly):
--
-- 1. This ENTIRE file applied (CREATE TABLE + backfill INSERT, as one
--    script, the normal case): every existing institution has an
--    explicit InstitutionEntitlement row the instant this script
--    finishes — there is no gap, no matter how soon application code
--    that reads it starts running afterward. Access is preserved
--    exactly per the mapping table above.
--
-- 2. Only the CREATE TABLE/enum/index/FK statements applied, backfill
--    NOT yet run (e.g. someone runs only the DDL portion): the table
--    exists but is empty. Application code's fallback
--    (evaluateInstitutionEntitlement(null, now) -> effectiveStatus
--    "ACTIVE", every canInstitutionUseFeature check -> allowed) treats
--    every institution as fully active/unlimited/all-features-on in the
--    interim — see institutionEntitlement.ts's own file-level doc
--    comment. No institution is locked out; nothing is over-restricted
--    either (a SUSPENDED institution would incorrectly still work until
--    the backfill runs) — this state should be kept as brief as
--    possible, but it is never an outage.
--
-- 3. Migration applied, prisma/seed.ts NOT run, application starts
--    immediately: no difference from scenario 1 above — the backfill
--    INSERT in THIS file already did seed.ts's job for every real
--    institution. prisma/seed.ts's own entitlement backfill
--    (mapLegacyInstitutionToEntitlementInput via the same LEFT JOIN ...
--    WHERE NULL idempotent pattern) is retained purely for local/dev
--    databases seeded from scratch — it is not, and was never meant to
--    be, the production backfill mechanism. Running it again anyway
--    (e.g. as part of a later deploy step) is harmless: it inserts zero
--    additional rows, since every institution already has one from this
--    file.
-- ---------------------------------------------------------------------
