/**
 * Tether Secure Client Foundation v1 — plain (unencrypted) Safe Exam
 * Browser `.seb` configuration generator. See
 * docs/secure-client-foundation-seb-v1.md and Part 4 of the spec.
 *
 * Pure, dependency-free: no Prisma, no Next.js. Generates a standards-
 * compliant Apple XML property list (plist) — the documented, plain
 * (unencrypted) `.seb` file format. Deliberately implements only a
 * conservative, DOCUMENTED ALLOWLIST of well-established SEB
 * configuration keys (see `SUPPORTED_KEYS` below) rather than the full
 * SEB settings surface, since this repository has no way to validate
 * against a real SEB client build during development — see
 * docs/secure-client-foundation-seb-v1.md, "Known limitations", for the
 * explicit recommendation to validate any generated file against a real
 * SEB client before relying on it for a live exam.
 *
 * PASSWORD- AND CERTIFICATE-ENCRYPTED `.seb` GENERATION IS NOT
 * IMPLEMENTED. Institutions may upload an administrator-generated
 * encrypted configuration instead (see the "Administrator-provided
 * configuration" path in docs/secure-client-foundation-seb-v1.md). This
 * module never claims to produce an encrypted file.
 *
 * Generation is fully deterministic: the same input always produces
 * byte-identical output, so `computeSebConfigHash` is stable and the
 * exact generated bytes can be preserved/re-derived at any time.
 */
import { createHash } from "crypto";

export type SebConfigInput = {
  startUrl: string;
  quitUrl: string;
  allowedOrigins: string[];
  allowPrinting: boolean;
  allowClipboard: boolean;
  allowExternalNavigation: boolean;
  /**
   * Single Display Requirement v1 — see
   * docs/secure-client-foundation-seb-v1.md, "Display requirement", and
   * isDisplayPolicyCombinationValid() in src/lib/secureClientPolicy.ts
   * (the caller must already have confirmed this combination is valid —
   * this generator does not re-validate delivery mode). When true, the
   * generated configuration sets both `allowDisplayMirroring` (false) and
   * `allowedDisplaysMaxNumber` (see SINGLE_DISPLAY_MAX_COUNT below); when
   * false, both keys are omitted entirely rather than guessing an
   * "unlimited"/"allowed" sentinel value that isn't documented anywhere.
   */
  singleDisplayRequired: boolean;
  configurationName: string;
};

/**
 * SEB's own documented display-restriction settings. Both
 * `allowDisplayMirroring` and `allowedDisplaysMaxNumber` are confirmed by
 * the official SEB developer config-key reference
 * (safeexambrowser.org/developer/seb-config-key.html), which lists them
 * together — `allowDisplayMirroring` (example value `false`) and
 * `allowedDisplaysMaxNumber` (example value `1`, described there as
 * "specifies the maximum number of displays that can be connected") — and
 * by an official SafeExamBrowser demo `.seb` file (SafeExamBrowser/
 * SafeExamBrowser-Website on GitHub) using
 * `<key>allowedDisplaysMaxNumber</key><integer>3</integer>`.
 *
 * What this codebase claims, and no more:
 *   - `allowedDisplaysMaxNumber` is the documented SEB
 *     maximum-connected-display setting.
 *   - `allowDisplayMirroring=false` explicitly disables display mirroring
 *     on supported SEB platforms.
 *   - Limiting the allowed display count to one prevents operation with
 *     more than one display where SEB's display validation supports it.
 *   - Real-device validation against an actual SEB installation is still
 *     required before relying on this for a live exam — see the manual
 *     checklist in docs/secure-client-foundation-seb-v1.md.
 * Value is an integer; this codebase only ever writes 1 (omitting both
 * keys entirely for "no restriction" — see
 * SebConfigInput.singleDisplayRequired above) since a "0 means unlimited"
 * sentinel is not documented anywhere this project could verify.
 */
export const SINGLE_DISPLAY_MAX_COUNT = 1;

/** The exact, documented set of plist keys this generator ever writes — nothing outside this list, and never a secret validation key in a student-readable field. */
export const SUPPORTED_SEB_CONFIG_KEYS = [
  "startURL",
  "quitURL",
  "quitURLConfirm",
  "allowQuit",
  "browserWindowAllowReload",
  "newBrowserWindowByLinkPolicy",
  "urlFilterEnable",
  "urlFilterEnableContentFilter",
  "URLFilterRules",
  "allowSpellCheck",
  "enablePrintScreen",
  "allowPrintScreen",
  "browserWindowAllowExternalNavigation",
  "allowDisplayMirroring",
  "allowedDisplaysMaxNumber",
  "originatorVersion",
  "sebConfigPurpose",
] as const;

function xmlEscape(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

type PlistValue = string | number | boolean | PlistValue[] | { [key: string]: PlistValue };

function plistNode(value: PlistValue, indent: string): string {
  if (typeof value === "boolean") return `${indent}<${value ? "true" : "false"}/>`;
  if (typeof value === "number") return `${indent}<integer>${Math.trunc(value)}</integer>`;
  if (typeof value === "string") return `${indent}<string>${xmlEscape(value)}</string>`;
  if (Array.isArray(value)) {
    if (value.length === 0) return `${indent}<array/>`;
    return [`${indent}<array>`, ...value.map((v) => plistNode(v, indent + "\t")), `${indent}</array>`].join("\n");
  }
  const keys = Object.keys(value); // Insertion order is preserved deliberately — see buildSebConfigDict, which always builds keys in SUPPORTED_SEB_CONFIG_KEYS order for determinism.
  if (keys.length === 0) return `${indent}<dict/>`;
  const lines: string[] = [`${indent}<dict>`];
  for (const key of keys) {
    lines.push(`${indent}\t<key>${xmlEscape(key)}</key>`);
    lines.push(plistNode(value[key], indent + "\t"));
  }
  lines.push(`${indent}</dict>`);
  return lines.join("\n");
}

function buildSebConfigDict(input: SebConfigInput): Record<string, PlistValue> {
  // Built strictly in SUPPORTED_SEB_CONFIG_KEYS order — deterministic
  // output regardless of caller-supplied field order.
  // allowDisplayMirroring/allowedDisplaysMaxNumber (see
  // SINGLE_DISPLAY_MAX_COUNT above) are the two conditional keys: only
  // added together — at their documented position, right before
  // originatorVersion — when singleDisplayRequired is true; both omitted
  // entirely otherwise ("UNRESTRICTED does not add single-display
  // enforcement"). Deliberately does NOT set allowedDisplayBuiltin — the
  // policy requires one active display, not specifically the device's
  // built-in display.
  const dict: Record<string, PlistValue> = {
    startURL: input.startUrl,
    quitURL: input.quitUrl,
    quitURLConfirm: true,
    allowQuit: true,
    browserWindowAllowReload: true,
    newBrowserWindowByLinkPolicy: 0,
    urlFilterEnable: true,
    urlFilterEnableContentFilter: true,
    URLFilterRules: input.allowedOrigins.map((origin) => ({
      active: true,
      regex: false,
      expression: `${origin}/*`,
      action: 1,
    })),
    allowSpellCheck: false,
    enablePrintScreen: input.allowPrinting,
    allowPrintScreen: input.allowPrinting,
    browserWindowAllowExternalNavigation: input.allowExternalNavigation,
  };
  if (input.singleDisplayRequired) {
    dict.allowDisplayMirroring = false;
    dict.allowedDisplaysMaxNumber = SINGLE_DISPLAY_MAX_COUNT;
  }
  dict.originatorVersion = "Tether Secure Client Foundation v1";
  dict.sebConfigPurpose = 0;
  return dict;
}

/** Generates the plain (unencrypted) `.seb` file bytes (UTF-8 XML plist) — deterministic for a given input. Clipboard policy is enforced via urlFilter/navigation restriction, not a dedicated documented plist key in this conservative key set — see "Known limitations". */
export function generatePlainSebConfig(input: SebConfigInput): string {
  void input.allowClipboard;
  void input.configurationName;
  const dict = buildSebConfigDict(input);
  const body = plistNode(dict, "\t");
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">',
    body,
    "</plist>",
    "",
  ].join("\n");
}

/** SHA-256 hex digest of the generated bytes — a deterministic configuration hash, stable across regenerations of the same input. */
export function computeSebConfigHash(configBytes: string): string {
  return createHash("sha256").update(configBytes, "utf8").digest("hex");
}

export const ENCRYPTED_SEB_CONFIG_UNAVAILABLE_MESSAGE =
  "Password-encrypted and certificate-encrypted SEB configuration generation is not available in v1. Institutions may upload an administrator-generated encrypted configuration.";
